### ISSUE TITLE
appsettings.local.json gets created as dir

### ISSUE THREAD

**Issue by chucker** [trenz-gmbh/trenz-docs-api#1]
If missing, docker(?) seems to create `appsettings.local.json` as an empty directory, not as a file.

**Comment by ricardoboss** [comment]
Possible workarounds:

https://stackoverflow.com/a/59554543/5107884

https://docs.docker.com/compose/compose-file/compose-file-v3/#long-syntax-3

So the `docker-compose.yml` needs to be changed like this, I suppose:

```yml
version: "3.9"
services:
  api:
    ...
    volumes:
      - type: bind
        source: ./appsettings.local.json
        target: /app/appsettings.local.json
```
